# @package _group_
task: denoising
phases: [
    {ep: [0, 40], lr: [0.0001, 0.000005], mode: cos, mom: null},
]
size: 768
metrics: [mse, huber]
criterion: mse
criterion_params: {}

segm_arch: unet
arch: se_resnet50
model_params:
  pretrained: 'imagenet'