
# General
name: default
task: denoising
seed: 42
root: data/raw
batch_size: 32
workers: 4
aug_type: light
debug: false
resume: ""

# Model
segm_arch: unet
arch: se_resnet50
model_params: {pretrained: 'imagenet'}
ema_decay: 0.0

# Training
optim: adam
optim_params: {weight_decay: 0.0, amsgrad: true}
use_fp16: true
size: 256
phases: [
    {ep: [0, 20], lr: [0.00005, 0.000001]},
]
metrics: [huber, mae, mse]

criterion: mae
criterion_params: {}

# Validation and testing
tta: false