defaults:
  - training: classification

general:
  name: default
  seed: 42
  debug: false
  base_dir: ./

data:
  root: data/raw
  batch_size: 32
  workers: 6
  aug_type: light

training:
  resume: ""
  optim: adam
  optim_params:
    weight_decay: 0.0
    amsgrad: true
  use_fp16: true
  ema_decay: 0.0

  model:
    arch: resnet50
    model_params:
      pretrained: 'imagenet'
  
testing:
  val_size: 512
  tta: false

# hydra:
#   job:
#     env_set:
#       CUDA_VISIBLE_DEVICES: "[1, 2, 3]"
#       HYDRA_FULL_ERROR: "1"
# hydra:
#   job:
#     env_set:
#       CUDA_VISIBLE_DEVICES: 1

hydra:
  # output_subdir: null
  # output_subdir: ""
  run:
    dir: logs/${general.name}_${now:%Y_%m_%d_%H_%M}
  sweep:
    dir: logs/${general.name}_${now:%Y_%m_%d_%H_%M}
    subdir: ""
  job_logging:
    version: 1
    formatters:
      simple:
        # format: '[%(levelname)s] - %(message)s'
        # format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
        format: '%(levelname)s %(module)s.%(funcName)s: %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      handlers: [console]
    file:
      class: logging.FileHandler
      formatter: simple
      filename: ${hydra.job.name}.log





