defaults:
  - training: classification

general:
  name: default
  seed: 42
  debug: false

data:
  root: data/raw
  batch_size: 32
  workers: 6
  aug_type: light

training:
  resume: ""
  optim: adam
  optim_params:
    weight_decay: 0.0
    amsgrad: true
  use_fp16: true
  ema_decay: 0.0
  
testing:
  val_size: 512
  tta: false

hydra:
  # output_subdir: ""
  run:
    dir: logs/${general.name}_${now:%Y_%m_%d_%H_%M}
  sweep:
    dir: logs/${general.name}_${now:%Y_%m_%d_%H_%M}
    subdir: ""





